apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: litecoind
    app: litecoind
  name: litecoind
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: litecoind
    spec:
      containers:
        - name: litecoind
          image: kuberstack/litecoind
          imagePullPolicy: Always
          ports:
            - containerPort: 443
              name: litecoind-rpc
          volumeMounts:
            - mountPath: /root
              name: litecoind-pvc
            - mountPath: /etc/litecoind
              name: litecoind-conf
              readOnly: true
            - mountPath: /etc/litecoind-ssl
              name: litecoind-ssl
              readOnly: true
          resources:
            requests:
              cpu: 0.5
              memory: 512Mi
            limits:
              cpu: 4
              memory: 10000Mi
      volumes:
        - name: litecoind-pvc
          persistentVolumeClaim:
            claimName: litecoind-pvc
        - name: litecoind-conf
          secret:
            secretName: litecoind-conf
        - name: litecoind-ssl
          secret:
            secretName: litecoind-ssl
